package cn.hiproject.pm.server.mybatis.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_id
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.account_full_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String accountFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.country
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_id
     *
     * @return the value of account.account_id
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_id
     *
     * @param accountId the value for account.account_id
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_name
     *
     * @return the value of account.account_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_name
     *
     * @param accountName the value for account.account_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.account_full_name
     *
     * @return the value of account.account_full_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getAccountFullName() {
        return accountFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.account_full_name
     *
     * @param accountFullName the value for account.account_full_name
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setAccountFullName(String accountFullName) {
        this.accountFullName = accountFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.status
     *
     * @return the value of account.status
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.status
     *
     * @param status the value for account.status
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.country
     *
     * @return the value of account.country
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.country
     *
     * @param country the value for account.country
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.email
     *
     * @return the value of account.email
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.email
     *
     * @param email the value for account.email
     *
     * @mbg.generated Fri Feb 24 16:54:04 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }
}